CREATE TABLE "GCG_6839_SALES_TAX"(
 "CUSTOMER" CHAR(6),
 "NAME_CUSTOMER" CHAR(30),
 "TAX_EXMP_NO" CHAR(20),
 "TAX_STATE" CHAR(2),
 "EXP_DATE" DATE,
 "DATE_LST_SENT" DATE,
 "DATE_LST_REC" DATE,
 "EMAIL_ADDRESS" LONGVARCHAR,
 "PRINT_FLAG" BIT NOT NULL );
